version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
      
    volumes:
      - ./ngnix-config/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - auth
      - post 

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    # ports:
    #   - "6000:6000"

    deploy:
     replicas: 1

  post:
    build:
      context: ./post
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"

    deploy:
      replicas: 1
